### PR TITLE
update morula

### PR DESCRIPTION
**Pull request by hugoesthere**
Update morula take 2

### CODE REVIEW

**Comment by martinjaime** [comment]
Why would the error be that the documentation directory has no `bin/setup`?

**Comment by hugoesthere** [comment]
@martinjaime that's what I'm trying to figure out. I've put up two different PRs both with `bin/setup` that I can execute locally. Not sure why Travis can't find that file..

**Comment by martinjaime** [comment]
@hugobho, to repeat what I messaged on slack, it also seems to be running commands in hidden directories even though morula is supposed to ignore them.

**Comment by hugoesthere** [comment]
Another branch making the same changes has been merged into master.

**Pull request closed without merging**
