### PR TITLE
reduce output on ci

### PR DESCRIPTION
**Pull request by charlierudolph**

### CODE REVIEW

**Review by hugoesthere — APPROVED** [review]
:1st_place_medal:

**Comment by charlierudolph** [comment]
Nearly 5000 lines becomes around 150. I'll address the remaining output
```
File generated: ...
```
in another PR

**Comment by charlierudolph** [comment]
This PR converts cucumber format from pretty to progress and silences the output of the observable process but makes it easy to opt in with an env variable

**Review by hugoesthere — APPROVED** [review]
Looks good, thanks for the cleanup.

**Pull request merged**
