### PR TITLE
exit route53-updater on local run

### PR DESCRIPTION
**Pull request by hugoesthere**

### CODE REVIEW

**Review by charlierudolph — APPROVED** [review]

**Comment by charlierudolph** [comment]
Can we also update the documentation so the user knows this was designed to not run locally with `exo run --production`?

**Comment by hugoesthere** [comment]
Where would that documentation belong? In the same place we should also list that `ROLE` is passed as well

**Comment by charlierudolph** [comment]
I was thinking next to the `update-route53` documentation in `service.md`

**Comment by charlierudolph** [comment]
closing in favor of #977

**Pull request closed without merging**
