### PR TITLE
Modify goprompt to accept spaces between strings

### LINKED ISSUE #524: exo configure - cannot deal with secret values having spaces
When entering a value which contains a whitespace, the part after the whitespace is used as the next key

### PR DESCRIPTION
**Pull request by hugoesthere**
Meant to resolve https://github.com/Originate/exosphere/issues/524

#524 is an issue stemming from the package we're using, not our code itself. I'm not sure if it's okay updating the vendor files manually like this. We could always fork segmentio/go-prompt. Alternatively, there are people who have already made these changes:
https://github.com/jandre/go-prompt
https://github.com/kofalt/go-prompt

### CODE REVIEW

**Comment by charlierudolph** [comment]
I think we need to update glide to install from the fork. Otherwise this could be overwritten the next time we update dependencies (which happens anytime we add/remove a dependency)

**Comment by hugoesthere** [comment]
Ok, should we just use one of those forks then?

**Comment by charlierudolph** [comment]
Yes please

**Comment by hugoesthere** [comment]
@charlierudolph switched to forked repo

**Review by charlierudolph — APPROVED** [review]

**Pull request merged**
