### PR TITLE
remove service.yml setup command

### PR DESCRIPTION
**Pull request by charlierudolph**
This is no longer used. The tutorial test will fail until I update the templates (which would cause master to fail until this is merged). Once I get a review here, I will do that.

Related: Thoughts on updating template support in order to specify a tag / commit sha? That way you don't always install the latest on the default branch but can install a particular version of the repo.

### CODE REVIEW

**Comment by kevgo** [comment]
You mean install a certain older (stable) version of templates? Why can't we always install the latest version from master?

**Comment by charlierudolph** [comment]
Yes. Maybe in the case that master has a bug. It would be useful just for our testing purposes so we are using a stable version of the template. Thus when the template gets updated, it can't break the exosphere tests.

**Comment by kevgo** [comment]
Hmm, good idea. Maybe make it an optional argument?

**Comment by charlierudolph** [comment]
Yeah thats what I was thinking

**Review by hugoesthere — APPROVED** [review]
👍 

I'm for attaching commit shahs to templates as well.

**Comment by charlierudolph** [comment]
Going to close since this is blocked by #407

**Pull request closed without merging**
