### PR TITLE
Simplify logger for exo clean

### PR DESCRIPTION
**Pull request by hugoesthere**
Resolves pt 1 of https://github.com/Originate/exosphere/issues/699

### CODE REVIEW

**Comment by charlierudolph** [comment]
Can you please add an example of what the output of exo-clean will look like?

**Comment by hugoesthere** [comment]
Example:
screen shot 2017-10-25 at 2 11 40 pm

**Comment by charlierudolph** [comment]
Lets remove "We are about to clean up your docker workspace!". Also can you check if we can get any output for removing the dangling images and dangling volumes). When running the docker command for them it lists what got deleted. If that is available easily great, otherwise don't worry about it for now.

**Review by charlierudolph — APPROVED** [review]

**Comment by hugoesthere** [comment]
exo clean output:
screen shot 2017-10-25 at 3 50 46 pm

**Review by charlierudolph — APPROVED** [review]
Merge on green

**Pull request merged**
