### PR TITLE
Switch exo deploy to io.writer

### PR DESCRIPTION
**Pull request by hugoesthere**
Resolving https://github.com/Originate/exosphere/issues/699

### CODE REVIEW

**Comment by charlierudolph** [comment]
Can you please add an example of what the output of `exo-deploy` will look like?

**Comment by hugoesthere** [comment]
Example output:
screen shot 2017-10-25 at 2 13 27 pm
screen shot 2017-10-25 at 2 14 59 pm
screen shot 2017-10-25 at 2 14 32 pm

**Comment by charlierudolph** [comment]
Lets remove "We are about to deploy an application". Ideally I think the banners should only be used when they are followed by the output of a child process. Unless the validations steps take a long time, I think we can remove those headers.

**Comment by charlierudolph** [comment]
Thoughts on the following: only use the banner rows when dealing with child processes. If there isn't going to be any output don't use a banner row and instead just print it. Thus the first 5 would all appear after each other with no lines of stars. The child process part could be updated to something like
```
Generating terraform files...
Retrieving remove state...
*******************************
<output>
*******************************
```
Then I'm fine keeping all the current messages and we are using the lines of stars only to separate output for child processes.

**Comment by hugoesthere** [comment]
So are we putting the banner around the child process itself or the "command" that signifies the start of the child process? Because in exo clean/template test we're doing the latter.

**Comment by charlierudolph** [comment]
I think we should move to putting it around the child process output as that what we want to separate from the rest.

**Comment by hugoesthere** [comment]
Ok, output looks closer to this now:
screen shot 2017-10-25 at 3 49 20 pm
screen shot 2017-10-25 at 3 49 37 pm

**Review by charlierudolph — APPROVED** [review]

**Pull request merged**
