### PR TITLE
exo run: stop printing exit error

### PR DESCRIPTION
**Pull request by charlierudolph**
Was seeing this in EDX:
```
Removing network edx_default
Removing network edx_default
WARNING: Network edx_default not found.
<<< done in 533.555538ms
panic: Error running 'docker-compose --file run_development.yml up --build': exit status 2

goroutine 1 [running]:
github.com/Originate/exosphere/src/cmd.glob..func10(0x1aaa6e0, 0x1ace1c0, 0x0, 0x0)
	/Users/charlesrudolph/go/src/github.com/Originate/exosphere/src/cmd/run.go:48 +0x2a9
github.com/Originate/exosphere/vendor/github.com/spf13/cobra.(*Command).execute(0x1aaa6e0, 0x1ace1c0, 0x0, 0x0, 0x1aaa6e0, 0x1ace1c0)
	/Users/charlesrudolph/go/src/github.com/Originate/exosphere/vendor/github.com/spf13/cobra/command.go:648 +0x231
github.com/Originate/exosphere/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1aaa4c0, 0xc420072058, 0x0, 0x1acdf0e)
	/Users/charlesrudolph/go/src/github.com/Originate/exosphere/vendor/github.com/spf13/cobra/command.go:735 +0x339
github.com/Originate/exosphere/vendor/github.com/spf13/cobra.(*Command).Execute(0x1aaa4c0, 0x1aaa4c0, 0xc4201b1f50)
	/Users/charlesrudolph/go/src/github.com/Originate/exosphere/vendor/github.com/spf13/cobra/command.go:693 +0x2b
github.com/Originate/exosphere/src/cmd.Execute()
	/Users/charlesrudolph/go/src/github.com/Originate/exosphere/src/cmd/root.go:18 +0x31
main.main()
	/Users/charlesrudolph/go/src/github.com/Originate/exosphere/src/cmd/exo/main.go:6 +0x20
```

This should stop us print exit status errors which aren't needed since all the output was printed to stdout

### CODE REVIEW

**Review by hugoesthere — APPROVED** [review]

**Comment by hugoesthere** [comment]
Looks like this caused a test to fail, though

**Comment by charlierudolph** [comment]
Removed that test as I don't think its useful anymore. We removed the dedicated setup part and I don't think the exit code of run matters

**Comment by charlierudolph** [comment]
Actually probably want to keep that as otherwise a build failure won't cause an exit

**Comment by charlierudolph** [comment]
@hugobho please review again as this completely changed. Dried up the code so we only shutdown once (after a manual shutdown or when the up command exits)

**Review by hugoesthere — APPROVED** [review]

**Pull request merged**
