### PR TITLE
release 0.27.0

### PR DESCRIPTION
**Pull request by charlierudolph**
https://github.com/Originate/exosphere/compare/v0.26.3...master

An awesome release. Thanks for all the great work guys!

### CODE REVIEW

**Review by hugoesthere — APPROVED** [review]

**Comment by hugoesthere** [comment]
One possible breaking change: when we switched the dynamodb read/write capacity from 5 to 1, I had to go into the web console and clear all the existing items. Not sure if this was the proper fix for the error I was running into but it seemed to have fixed it.

**Comment by charlierudolph** [comment]
If you didn't clear them, what error did you see?

**Comment by hugoesthere** [comment]
I forget exactly, I think it was something about not being able to get the item. I believe it happened during the `terraform init` step of deployment

**Comment by charlierudolph** [comment]
I don't believe I ran into that, because I basically deployed with 0.27.0 on already on EDX. Thanks for the heads up though.

**Pull request merged**
