### PR TITLE
exo test: build specific service & compose refactor

### PR DESCRIPTION
**Pull request by hugoesthere**
Resolves: https://github.com/Originate/exosphere/issues/735#issuecomment-342558698

### CODE REVIEW

**Comment by charlierudolph** [comment]
Can we also do this for `Run` in `src/docker/composerunner/run.go`?

**Comment by hugoesthere** [comment]
`Run` is used for `exo run`, and I think it actually makes more sense to separate the build&pull steps there, since those commands (at least the build) will only run if the image has change, whereas the `--build` flag will run build every time. For running a single service that's fine but when managing a whole application that's probably an unnecessary slowdown.

**Comment by charlierudolph** [comment]
I would expect `docker build` then `docker up` to be the same as `docker up --build`. Is that not true? Does `up --build` ignore the caches?

**Comment by hugoesthere** [comment]
Oh you're right, I thought `docker-compose build` was smart enough to skip if the image was built, like it does in `docker-compose up`. Looks like both cases uses the cache.

**Review by charlierudolph — APPROVED** [review]

**Pull request merged**
